# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crK01eeSLM2RH2mRfM2ePsbFv79q4jjK
"""

def timestable(x):
  for i in range(1,13):
    print(f"{i} times {x} is {i*x}")

my_input = input("Please enter a number between 1 and 12 ")
my_input = float(my_input)

if (my_input < 1) or (my_input > 12):
  print('Your input is out of bounds, try again')
  exit()
else:
  timestable(my_input)